security:
    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false
        login:
            pattern:  ^/session/login$
            security: false
        homepage:
            pattern: ^/$
            security: false
        default:
            anonymous: ~
            http_basic: ~
            form_login:
              check_path: /login_check
              login_path: /login
              #scsrf_parameter: _csrf_token
              #intention:      authenticate
              #csrf_provider:  form.csrf_provider
            logout:
                path:   /logout
                target: /
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER  }