imports:
    - { resource: security-base.yml }

security:
    encoders:
        Acme\UserBundle\Entity\User:
            algorithm: bcrypt

    providers:
        user_db:
            entity: { class: CWUserBundle:User, property: username }